ZO-4627: Handle empty tag nodes
See https://app.bugsnag.com/zeit-online-gmbh/friedbert/errors/65de03aee621ca0008b73b7f

GET /digital/games/2012-08/games-studie-marktentwicklung
  File "zeit/retresco/tagger.py", line 78, in <genexpr>
          return (self._create_tag(node.text, node.get('type', '')) for node in tags.iterchildren())
  File "zeit/retresco/tagger.py", line 167, in _create_tag
          tag = Tag(label, entity_type)
  File "zeit/cms/tagging/tag.py", line 62, in __init__
          self.__name__ = self.code  # needed to fulfill `ICMSContent`
  File "zope/cachedescriptors/property.py", line 109, in __get__
          value = func(inst)
  File "zeit/cms/tagging/tag.py", line 74, in code
          return ''.join((self.entity_type, self.SEPARATOR, self.label))
TypeError: sequence item 2: expected str instance, NoneType found