ZO-1629: Work around NonRecordingSpan opentelemetry bug
AFAICT otel violates its own API here, should use get_span_context() instead:
  File "opentelemetry/instrumentation/utils.py", line 160, in _generate_opentelemetry_traceparent
    _span_id = trace.format_span_id(span.context.span_id)
  AttributeError: 'NonRecordingSpan' object has no attribute 'context'

I'm backporting https://github.com/open-telemetry/opentelemetry-python-contrib/pull/1200
which sidesteps the issue by using propagate to generate the traceparent header
instead of doing it manually.